[skip ci] Second reference for cumsum
I implemnted a second reference for cumsum. It uses a divide and conquer
algorithm, but it's simpler than the one from JAX.

Of course, this decomposition is expected to be a trainwreck when it comes
to efficiency in triton. Even more, when adding the following
decomposition to TorchInductor:

```python
register_decomposition([prims.slice_in_dim])
def slice_in_dim(a, start_index, limit_index, stride=1, axis=0):
    return aten.slice(a, dim=axis, start=start_index, end=limit_index, step=stride)
```
and running it with a tenosr of size `[256, 256, 256]` and `dim=-1`,
TorchInductor breaks with the following trace:

```
  File "benchmark.py", line 44, in compare
    compiled_decomposed = compile_fx_inner(decomposed, [x])
  File "/home/lezcano/git/pytorch/torchdynamo/torchdynamo/debug_utils.py", line 377, in debug_wrapper
    compiled_fn = compiler(gm, example_inputs, **kwargs)
  File "/home/lezcano/git/pytorch/torchdynamo/torchinductor/debug.py", line 183, in inner
    return fn(*args, **kwargs)
  File "/home/lezcano/.conda/envs/pytorch-dev/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/lezcano/git/pytorch/torchdynamo/torchinductor/compile_fx.py", line 100, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/home/lezcano/git/pytorch/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/lezcano/git/pytorch/torchdynamo/torchinductor/compile_fx.py", line 152, in cudagraphify
    return cudagraphify_impl(model, inputs, static_input_idxs)
  File "/home/lezcano/git/pytorch/torchdynamo/torchinductor/compile_fx.py", line 217, in cudagraphify_impl
    model(*static_inputs)
  File "/tmp/torchinductor_lezcano/f2/cf2iurl6trc5fjye3ijev73l36rhiycw5gd4hjql7hs7qxlsh3u2.py", line 3293, in call
    kernel0.run(x_1, buf0, buf1, 65536, grid=grid(65536), stream=stream0)
  File "/home/lezcano/git/pytorch/torchdynamo/torchinductor/triton_ops/autotune.py", line 158, in run
    return launcher(
  File "<string>", line 4, in launcher
TypeError: function takes exactly 14 arguments (11 given)
```

The relevant triton code is awful as well. It generates 141
almost-identical kernels.

I am leaving this here not to be merged, but to investigate the crash
and the fact that it generates all those identical kernels.

ghstack-source-id: 002e2bf99439acf83aef6f3107bd6379189c612f
Pull Request resolved: https://github.com/pytorch/pytorch/pull/86372