better error message fix (#86422) (#86422)
Summary:
A user had a problem with fx-scripting and the error message can be improved.

Error was shown as:

RuntimeError: Keys for dictionaries used as an argument cannot contain a Node. Got key: {k}

which is obvious not quite helpful.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/86422
Approved by: https://github.com/SherlockNoMad

Test Plan:
contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/04490e90ea59229355b2771893719fe8896e80f0

Test plan from GitHub:
Test in a notebook:
{F778667593}

Reviewed By: seemethere, xunnanxu, SherlockNoMad

Differential Revision: D40157518

fbshipit-source-id: c0c1be5680643b414f3fc6f8e3b6a5130bc9795e