Ensure the minimum NVIDIA driver version to be 515.57 for CUDA 11.7 (#86344) (#86344)
Summary:
This does 2 things:

* Ensure that `nvidia-driver-latest-dkms` package is removed if it's installed. This allows the installation to go forward without the below error when using the standard installation script from S3:

```
(Answer: Abort installation)
ERROR: The installation was canceled due to the availability or presence of an alternate driver installation. Please see /var/log/nvidia-installer.log for more details.
```

* Not skipping the installation if a driver different than `515.57` exists to avoid any unexpected behavior when using a different driver version. This partly addresses the recent issue in https://github.com/pytorch/pytorch/issues/85778 in which `510.60.02` is there instead (not sure from where) and fails CUDA 11.7 test

Pull Request resolved: https://github.com/pytorch/pytorch/pull/86344
Approved by: https://github.com/atalman, https://github.com/malfet

Test Plan: contbuild & OSS CI, see https://hud.pytorch.org/commit/pytorch/pytorch/b8b564c90872316fe84fc781631afed5e78e069a

Reviewed By: seemethere

Differential Revision: D40167104

Pulled By: huydhn

fbshipit-source-id: af667a82a38a67974ba618b5a40321ecd1d58790